[package]
name = "discord_bot_rs"
version = "1.6.16"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.5"
ron = "0.8.0"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
rand = "0.8.5"
regex = "1.8.1"
chrono = "0.4.24"
chrono-tz = { version = "0.8.2", features = ["serde"] }
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.17"
lazy_static = "1.4.0"
anyhow = "1.0.71"
# Custom libraries
owm-rs = { version = "1.0.13", features = ["utils"] }
