[package]
name = "discord_bot_rs"
version = "1.6.15"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.5"
ron = "0.8.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
rand = "0.8.5"
regex = "1.7.3"
chrono = "0.4.24"
chrono-tz = { version = "0.8.1", features = ["serde"] }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.16"
lazy_static = "1.4.0"
anyhow = "1.0.70"
# Custom libraries
owm-rs = { version = "1.0.12", features = ["utils"] }
