[package]
name = "discord_bot_rs"
version = "1.6.14"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.5"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
rand = "0.8.5"
regex = "1.7.1"
chrono = "0.4.23"
chrono-tz = { version = "0.8.1", features = ["serde"] }
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.14"
lazy_static = "1.4.0"
anyhow = "1.0.68"
# Custom libraries
owm-rs = "1.0.7"
