[package]
name = "discord_bot_rs"
version = "1.3.19"
authors = ["Oscuro87"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[env]
sqlite3 = { value = "e:\\dlls", relative = false }

[dependencies]
serenity = "0.10.9"
ron = "0.6.5"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
rand = "0.8.4"
regex = "1.5.4"
chrono = "0.4.19"
tokio = { version = "1.11.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.4"
