[package]
name = "discord_bot_rs"
version = "1.5.2"
authors = ["Oscuro87"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[env]
#sqlite3 = { value = "e:\\dlls", relative = false }

[dependencies]
serenity = "0.10.9"
ron = "0.7.0"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.69"
rand = "0.8.4"
regex = "1.5.4"
chrono = "0.4.19"
chrono-tz = { version = "0.6.0", features = ["serde"] }
tokio = { version = "1.13.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.6"
lazy_static = "1.4.0"
