[package]
name = "discord_bot_rs"
version = "0.0.1"
authors = ["Oscuro87"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.5"
ron = "0.6.4"
serde = "1.0.125"
serde_derive = "1.0.125"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"] }
