[package]
name = "discord_bot_rs"
version = "1.6.8"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.2"
ron = "0.7.1"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
rand = "0.8.5"
regex = "1.6.0"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.11"
lazy_static = "1.4.0"
