[package]
name = "discord_bot_rs"
version = "1.3.5"
authors = ["Oscuro87"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.8"
ron = "0.6.4"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
rand = "0.8.4"
regex = "1.5.4"
chrono = "0.4.19"
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.4"
