[package]
name = "discord_bot_rs"
version = "1.6.14"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.5"
ron = "0.8.0"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
rand = "0.8.5"
regex = "1.7.0"
chrono = "0.4.23"
chrono-tz = { version = "0.8.0", features = ["serde"] }
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.13"
lazy_static = "1.4.0"
anyhow = "1.0.66"
# Custom libraries
owm-rs = { git = "https://github.com/Oscuro87/owm-rs.git", features = ["utils"] }
