[package]
name = "discord_bot_rs"
version = "1.6.9"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.5"
ron = "0.8.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
rand = "0.8.5"
regex = "1.6.0"
chrono = "0.4.22"
chrono-tz = { version = "0.6.3", features = ["serde"] }
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.11"
lazy_static = "1.4.0"
