[package]
name = "discord_bot_rs"
version = "1.6.3"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.10.10"
ron = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
rand = "0.8.5"
regex = "1.5.5"
chrono = "0.4.12"
chrono-tz = { version = "0.6.1", features = ["serde"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.10"
lazy_static = "1.4.0"
