[package]
name = "discord_bot_rs"
version = "1.0.1"
authors = ["Oscuro87"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.7"
ron = "0.6.4"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
lazy_static = "1.4.0"
rand = "0.8.3"
regex = "1.5.4"
chrono = "0.4.19"
url = "2.2.2"
reqwest = "0.11.3"

[dependencies.tokio]
version = "1.6.1"
features = ["macros", "rt-multi-thread"]
