[package]
name = "discord_bot_rs"
version = "1.6.7"
authors = ["Oscuro87"]
edition = "2021"
rust-version = "1.64.0"

[dependencies]
serenity = "0.11.2"
ron = "0.7.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
rand = "0.8.5"
regex = "1.5.6"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.11"
lazy_static = "1.4.0"
