[package]
name = "discord_bot_rs"
version = "1.6.10"
authors = ["Oscuro87"]
edition = "2021"

[dependencies]
serenity = "0.11.5"
ron = "0.8.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
rand = "0.8.5"
regex = "1.6.0"
chrono = "0.4.22"
chrono-tz = { version = "0.8.0", features = ["serde"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
reqwest = "~0.11.12"
lazy_static = "1.4.0"
anyhow = "1.0.66"
# Custom libraries
owm-rs = { git = "https://github.com/Oscuro87/owm-rs.git", version = "1.0.1", features = ["utils"] }
