name: Trigger Jenkins telling him rude things

on: [push]

jobs:
  build:
    name: trigger
    runs-on: ubuntu-latest
    steps:
    - name: Trigger job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.oscur.io"
        user: "emka87"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "discord-bot"
